### ISSUE TITLE
Hele loggboka

### ISSUE THREAD

**Issue by sindrehauglum** [hauglum/flightlog#1]
Fantastisk, det er mulig jeg skal spørre deg om litt hjelp for jeg skulle gjerne hatt tilsvarende data for hele loggboka per år siden 2011.
Dvs antall unike piloter, men gjerne fordelt på HG/PG/SPG
Mvh
Fagsjef HPS

**Comment by hauglum** [comment]
Godt forslag!

**Comment by hauglum** [comment]
done
